version: '3.8'

services:
  gstreamer_python:
    image: gstreamer_python:0.0.1
    container_name: gstreamer_python
    build: .
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix  # Mount the X11 Unix socket - Display window in container
      - /mnt/wslg/PulseServer:/mnt/wslg/PulseServer # PulseServer socket - Play audio in container
    environment:
      - DISPLAY=${DISPLAY}  # Pass the host DISPLAY variable - Display window in container
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer # Play audio in container
      - XDG_RUNTIME_DIR=/run/user/1/ # Prevent raise error message XDG_RUNTIME_DIR is invalid 
    network_mode: "host"
    tty: True
